Develop
homesengland/he-pipeline-assessment pull request #37
Opened 2022-10-14 08:25 UTC by jarekzaj

2022-10-14 08:56 UTC, rryan0088 approved these changes

2022-10-14 09:18 UTC, rryan0088 requested changes
Spotted a bug for the validator.  Will comment on the specific area.

2022-10-14 09:20 UTC, rryan0088 commented on src/He.PipelineAssessment.UI/Features/Workflow/SaveAndContinue/SaveAndContinueCommandValidator.cs
> +            RuleFor(x => x.Data.QuestionActivityData!.MultipleChoice).Must(multipleChoice =>
The command validator here does not filter based on the QuestionActivityData.ActivityType property - as such it blindly checks all queries, and as such hits issues when certain fields (in this instance SelectedChoices) is null.

2022-10-17 09:02 UTC, rryan0088 approved these changes

2022-10-17 09:03 UTC, Jonnythan-t approved these changes

2022-10-17 09:04 UTC, merged